#!/usr/bin/env bash
set -euo pipefail

: "${GITHUB_OUTPUT:?GITHUB_OUTPUT is required}"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
workflow_started_epoch=$(date +%s)
source_sha=${GITHUB_SHA:-HEAD}
if ! git merge-base "$source_sha" origin/main >/dev/null 2>&1; then
  for deepen_by in 64 128 256; do
    echo "Preflight merge base is unavailable; deepening by $deepen_by commits."
    "$script_dir/git-fetch-origin.sh" \
      --no-tags \
      --deepen="$deepen_by" \
      origin \
      "$source_sha" \
      main:refs/remotes/origin/main
    if git merge-base "$source_sha" origin/main >/dev/null 2>&1; then
      break
    fi
  done
fi
if ! git merge-base "$source_sha" origin/main >/dev/null 2>&1; then
  echo "Preflight merge base remains unavailable after bounded deepening." >&2
  exit 1
fi
low_risk_change=false
if ./ci/is-low-risk-ios-diff.sh origin/main "$source_sha"; then
  low_risk_change=true
fi
scope=$(
  IOS_LOW_RISK_CHANGE="$low_risk_change" ./ci/classify-ios-test-scope.sh \
    < <(git diff --name-only origin/main "$source_sha")
)
app_changed=$(awk -F= '$1 == "app_changed" { print $2 }' <<<"$scope")
test_scope=$(awk -F= '$1 == "test_scope" { print $2 }' <<<"$scope")
preflight_started_epoch=$workflow_started_epoch
preflight_finished_epoch_file=$(mktemp "${RUNNER_TEMP:-/tmp}/ios-preflight-finished.XXXXXX")

(
  set +e
  IOS_PREFLIGHT_SKIP_FETCH=true ./ci/linux-preflight.sh origin/main
  status=$?
  date +%s > "$preflight_finished_epoch_file"
  exit "$status"
) &
preflight_pid=$!

device_warm_started_epoch=$(date +%s)
device_warm_finished_epoch_file=$(mktemp "${RUNNER_TEMP:-/tmp}/ios-device-warm-finished.XXXXXX")
(
  status=0
  if [[ "$app_changed" == true && -n "${DEVICE_UDID:-}" ]]; then
    ./ci/report-ios-deployment.sh running 0.005 checking-device-stability || true
    if ! ./ci/probe-ios-device.sh; then
      ./ci/report-ios-deployment.sh failed 0 device-gate-failed || true
      status=1
    else
      ./ci/report-ios-deployment.sh running 0.01 device-gate-ready || true
    fi
  else
    echo "No App change requires a device build; skipping the iPhone stability gate."
  fi
  date +%s > "$device_warm_finished_epoch_file"
  exit "$status"
) &
device_warm_pid=$!

prepare_started_epoch=$(date +%s)
prepare_metrics_file=$(mktemp "${RUNNER_TEMP:-/tmp}/ios-prepare-metrics.XXXXXX")
export IOS_PREPARE_METRICS_FILE="$prepare_metrics_file"
if [[ "$app_changed" == true ]]; then
  IOS_SKIP_SIMULATOR_WARM=$([[ "$test_scope" == build ]] && echo true || echo false) \
    ./ci/prepare-central-runner.sh
else
  echo "Configuration-only change; skipping Xcode dependency and build cache warming."
  {
    echo "dependency_seconds=0"
    echo "device_build_warm_seconds=0"
    echo "simulator_warm_seconds=0"
  } > "$prepare_metrics_file"
fi

prepare_duration_seconds=$(($(date +%s) - prepare_started_epoch))
dependency_seconds=0
device_build_warm_seconds=0
simulator_warm_seconds=0
# The metrics file is generated by prepare-central-runner.sh in this process.
# shellcheck disable=SC1090
source "$prepare_metrics_file"

set +e
wait "$device_warm_pid"
device_warm_status=$?
wait "$preflight_pid"
preflight_status=$?
set -e
device_warm_finished_epoch=$(cat "$device_warm_finished_epoch_file")
device_warm_duration_seconds=$((device_warm_finished_epoch - device_warm_started_epoch))
preflight_finished_epoch=$(cat "$preflight_finished_epoch_file")
preflight_duration_seconds=$((preflight_finished_epoch - preflight_started_epoch))

{
  echo "started_epoch=$workflow_started_epoch"
  echo "preflight_duration_seconds=$preflight_duration_seconds"
  echo "duration_seconds=$prepare_duration_seconds"
  echo "device_warm_duration_seconds=$device_warm_duration_seconds"
  echo "dependency_duration_seconds=$dependency_seconds"
  echo "device_build_warm_duration_seconds=$device_build_warm_seconds"
  echo "simulator_warm_duration_seconds=$simulator_warm_seconds"
  echo "device_gate_failed=$([[ "$device_warm_status" -ne 0 ]] && echo true || echo false)"
} >> "$GITHUB_OUTPUT"

if [[ -n "${GITHUB_ENV:-}" ]]; then
  {
    echo "IOS_PREFLIGHT_SECONDS=$preflight_duration_seconds"
    echo "IOS_PREPARE_SECONDS=$prepare_duration_seconds"
    echo "IOS_DEVICE_WARM_SECONDS=$device_warm_duration_seconds"
    echo "IOS_DEPENDENCY_SECONDS=$dependency_seconds"
    echo "IOS_DEVICE_BUILD_WARM_SECONDS=$device_build_warm_seconds"
    echo "IOS_SIMULATOR_WARM_SECONDS=$simulator_warm_seconds"
    echo "IOS_WORKFLOW_STARTED_EPOCH=$workflow_started_epoch"
  } >> "$GITHUB_ENV"
fi

if [[ -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
  {
    echo "### Central Mac cache warm"
    echo
    echo "| Work | Duration |"
    echo "| --- | ---: |"
    echo "| Dependency resolution | ${dependency_seconds}s |"
    echo "| Device build cache (parallel) | ${device_build_warm_seconds}s |"
    echo "| Simulator boot + test build cache (parallel) | ${simulator_warm_seconds}s |"
    echo "| Wall-clock cache preparation | ${prepare_duration_seconds}s |"
  } >> "$GITHUB_STEP_SUMMARY"
fi

if ((preflight_status != 0)); then
  echo "Repository preflight failed with exit code $preflight_status." >&2
  exit "$preflight_status"
fi
if ((device_warm_status != 0)); then
  echo "iPhone stability gate failed with exit code $device_warm_status." >&2
  exit "$device_warm_status"
fi
